# Generated by Django 5.1.4 on 2024-12-15 10:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Form Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='EmailQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Question Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('question_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('email', 'Email'), ('numeric', 'Numeric')], max_length=20, verbose_name='Type')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
            options={
                'default_related_name': 'email_questions',
            },
        ),
        migrations.CreateModel(
            name='LongTextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Question Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('question_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('email', 'Email'), ('numeric', 'Numeric')], max_length=20, verbose_name='Type')),
                ('max_length', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5000)], verbose_name='Max Length')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
            options={
                'default_related_name': 'long_text_questions',
            },
        ),
        migrations.CreateModel(
            name='NumericQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Question Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('question_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('email', 'Email'), ('numeric', 'Numeric')], max_length=20, verbose_name='Type')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Value')),
                ('is_decimal_allowed', models.BooleanField(default=False, verbose_name='Allow Decimals')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
            options={
                'default_related_name': 'numeric_questions',
            },
        ),
        migrations.CreateModel(
            name='ShortTextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Question Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('question_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('email', 'Email'), ('numeric', 'Numeric')], max_length=20, verbose_name='Type')),
                ('max_length', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(250)], verbose_name='Max Length')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
            options={
                'default_related_name': 'short_text_questions',
            },
        ),
    ]
